# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Configurando ambiente JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: artifactory
          server-username: MAVEN_REPO_USER
          server-password: MAVEN_REPO_PASS
          
      - name: Excutando os testes
        run: mvn test
        env:
          MAVEN_REPO_PASS: ${{ secrets.MAVEN_REPO_PASS }}
          MAVEN_REPO_USER: ${{ secrets.MAVEN_REPO_USER }}
        
